<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217184332 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tree (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        // Supprimer les tables seulement si elles existent
        $this->addSql('DROP TABLE IF EXISTS leads CASCADE');
        $this->addSql('DROP TABLE IF EXISTS quiz_edges CASCADE');
        $this->addSql('DROP TABLE IF EXISTS quiz_nodes CASCADE');
        $this->addSql('DROP TABLE IF EXISTS quiz_trees CASCADE');
        // Ajouter la colonne created_at avec une valeur par défaut pour les enregistrements existants
        $this->addSql('ALTER TABLE jobs ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW()');
        // Mettre à jour les enregistrements existants (si nécessaire)
        $this->addSql("UPDATE jobs SET created_at = NOW() WHERE created_at IS NULL");
        // Ajouter la contrainte NOT NULL
        $this->addSql('ALTER TABLE jobs ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE jobs ALTER id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE jobs ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey');
        $this->addSql('ALTER TABLE profiles ADD email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE profiles ALTER role TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE profiles ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE profiles ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE quiz_session_answers ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER question_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER answer_id TYPE VARCHAR(255)');
        $this->addSql('ALTER INDEX idx_answers_session RENAME TO IDX_790CFE0D613FECDF');
        // Supprimer les contraintes et index seulement s'ils existent
        $this->addSql('ALTER TABLE quiz_sessions DROP CONSTRAINT IF EXISTS quiz_sessions_final_job_id_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_sessions_user');
        $this->addSql('DROP INDEX IF EXISTS IDX_4CA46456FBEEC5BE');
        $this->addSql('ALTER TABLE quiz_sessions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE quiz_sessions ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE quiz_sessions ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE quiz_sessions ALTER final_job_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores TYPE JSON');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores DROP DEFAULT');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE TABLE leads (id UUID DEFAULT \'gen_random_uuid()\' NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, user_id UUID DEFAULT NULL, session_id UUID DEFAULT NULL, email TEXT NOT NULL, phone TEXT DEFAULT NULL, consent BOOLEAN DEFAULT false NOT NULL, message TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_leads_user ON leads (user_id)');
        $this->addSql('CREATE INDEX IDX_17904552613FECDF ON leads (session_id)');
        $this->addSql('CREATE TABLE quiz_edges (id UUID DEFAULT \'gen_random_uuid()\' NOT NULL, tree_id UUID NOT NULL, from_node_id UUID NOT NULL, label TEXT NOT NULL, to_node_id UUID NOT NULL, weight JSONB DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_edges_from ON quiz_edges (from_node_id)');
        $this->addSql('CREATE INDEX idx_edges_tree ON quiz_edges (tree_id)');
        $this->addSql('CREATE INDEX IDX_43D97435C895A222 ON quiz_edges (to_node_id)');
        $this->addSql('CREATE TABLE quiz_nodes (id UUID DEFAULT \'gen_random_uuid()\' NOT NULL, tree_id UUID NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, body TEXT DEFAULT NULL, job_id TEXT DEFAULT NULL, meta JSONB DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_nodes_tree ON quiz_nodes (tree_id)');
        $this->addSql('CREATE INDEX IDX_E14E7C7CBE04EA9 ON quiz_nodes (job_id)');
        $this->addSql('CREATE TABLE quiz_trees (id UUID DEFAULT \'gen_random_uuid()\' NOT NULL, name TEXT NOT NULL, description TEXT DEFAULT NULL, version INT DEFAULT 1 NOT NULL, is_published BOOLEAN DEFAULT false NOT NULL, root_node_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT \'now()\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68AF162AAA4CD71D ON quiz_trees (root_node_id)');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT leads_session_id_fkey FOREIGN KEY (session_id) REFERENCES quiz_sessions (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_edges ADD CONSTRAINT quiz_edges_to_node_id_fkey FOREIGN KEY (to_node_id) REFERENCES quiz_nodes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_edges ADD CONSTRAINT quiz_edges_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES quiz_trees (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_edges ADD CONSTRAINT quiz_edges_from_node_id_fkey FOREIGN KEY (from_node_id) REFERENCES quiz_nodes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_nodes ADD CONSTRAINT quiz_nodes_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES quiz_trees (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_nodes ADD CONSTRAINT quiz_nodes_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_trees ADD CONSTRAINT quiz_trees_root_fk FOREIGN KEY (root_node_id) REFERENCES quiz_nodes (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE tree');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE jobs DROP created_at');
        $this->addSql('ALTER TABLE jobs ALTER id TYPE TEXT');
        $this->addSql('ALTER TABLE jobs ALTER name TYPE TEXT');
        $this->addSql('ALTER TABLE profiles DROP email');
        $this->addSql('ALTER TABLE profiles ALTER role TYPE TEXT');
        $this->addSql('ALTER TABLE profiles ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE profiles ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quiz_session_answers DROP created_at');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER id SET DEFAULT \'gen_random_uuid()\'');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER question_id TYPE TEXT');
        $this->addSql('ALTER TABLE quiz_session_answers ALTER answer_id TYPE TEXT');
        $this->addSql('ALTER INDEX idx_790cfe0d613fecdf RENAME TO idx_answers_session');
        $this->addSql('ALTER TABLE quiz_sessions ALTER id SET DEFAULT \'gen_random_uuid()\'');
        $this->addSql('ALTER TABLE quiz_sessions ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE quiz_sessions ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE quiz_sessions ALTER final_job_id TYPE TEXT');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores TYPE JSONB');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE quiz_sessions ALTER scores SET NOT NULL');
        $this->addSql('ALTER TABLE quiz_sessions ADD CONSTRAINT quiz_sessions_final_job_id_fkey FOREIGN KEY (final_job_id) REFERENCES jobs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_sessions_user ON quiz_sessions (user_id)');
        $this->addSql('CREATE INDEX IDX_4CA46456FBEEC5BE ON quiz_sessions (final_job_id)');
    }
}
